---

- name: Download taskd
  get_url:
    url: https://pkgbuild.com/~jelle/taskd-1.1.0-2-x86_64.pkg.tar.xz
    dest: /tmp/taskd.pkg.tar.xz

- name: Install taskd
  pacman: name="/tmp/taskd.pkg.tar.xz" state=present

- name: Setup CN for certificate generation
  lineinfile: dest=/usr/share/doc/taskd/pki/vars regexp="{{item.key}}" line="{{item.value}}"
  with_items:
          - { key: 'ORGANIZATION=', value: 'ORGANIZATION="{{ taskd_org }}"'}
          - { key: 'CN=', value: 'CN="{{ taskd_cn }}"'}

- name: Generate CA certificates
  command: ./generate chdir=/usr/share/doc/taskd/pki creates=/usr/share/doc/taskd/pki/ca.cert.pem

- name: Copy certificates to {{ taskd_home }}
  copy: remote_src=True src={{ taskd_pki_dir }}/{{ item }} dest={{ taskd_home }}/{{ item }} owner=taskd group=taskd
  with_items:
          - ca.cert.pem
          - ca.key.pem
          - server.cert.pem
          - server.crl.pem
          - server.key.pem
          - client.cert.pem
          - client.key.pem

- name: Set taskd config options
  command: "{{ item }}"
  with_items:
          - taskd config --data {{ taskd_home }} --force client.cert  {{ taskd_home }}/client.cert.pem
          - taskd config --data {{ taskd_home }} --force client.key  {{ taskd_home }}/client.key.pem
          - taskd config --data {{ taskd_home }} --force server.cert  {{ taskd_home }}/server.cert.pem
          - taskd config --data {{ taskd_home }} --force server.key  {{ taskd_home }}/server.key.pem
          - taskd config --data {{ taskd_home }} --force server.crl  {{ taskd_home }}/server.crl
          - taskd config --data {{ taskd_home }} --force ca.cert  {{ taskd_home }}/ca.cert.pem
          - taskd config --data {{ taskd_home }} --force server 0.0.0.0:{{ taskd_port }}

- name: Add taskd group
  command: taskd add org {{ taskd_org }} creates={{ taskd_home }}/orgs/{{ taskd_org }}
  become: true
  become_user: taskd
  environment:
          TASKDDATA: /var/lib/taskd

- name: Add taskd user
  command: taskd  add user {{ taskd_org }} {{ taskd_user }} creates={{ taskd_home }}/orgs/{{ taskd_org }}/users/{{ taskd_user }}
  become: true
  become_user: taskd
  environment:
          TASKDDATA: /var/lib/taskd

- name: generate client certificate
  command: ./generate.client {{ taskd_user }} chdir=/usr/share/doc/taskd/pki creates={{ taskd_pki_dir }}/jelle.cert.pem

- name: enable taskd systemd service
  systemd: state=started enabled=yes name=taskd
